#!/bin/sh -ue

# This script deploys a master or release version.
#
# See [README.md] for an explanation of this and how CI should use it.
version=${1:-master}

# Use implicit version when master, if we can..
if [ "${version}" = "master" ]; then
  version=$(sed -En 's/.*<version>(.*)<\/version>.*/\1/p' pom.xml| head -1)
fi

# TODO: remove -DignoreSnapshots=true after ES 8.14.0 is released
build-bin/maven/maven_deploy -DignoreSnapshots=true
export RELEASE_FROM_MAVEN_BUILD=true
build-bin/docker_push ${version}
