#!/bin/sh -ue

# Pushes docker as part of `deploy` or from a trigger tag
version=${1:-master}

# handle trigger pattern like /^docker-[0-9]+\.[0-9]+\.[0-9]+$/
case ${version} in
  docker-* )
    version=$(build-bin/git/version_from_trigger_tag docker- ${version})
    ;;
esac

build-bin/docker/docker_push openzipkin/zipkin-dependencies ${version}
