#!/bin/sh -ue

# Pushes docker as part of `deploy` or from a trigger tag
version=${1:-master}

# handle trigger pattern like /^docker-[0-9]+\.[0-9]+\.[0-9]+$/
case ${version} in
  docker-* )
    version=$(build-bin/git/version_from_trigger_tag docker- ${version})
    ;;
esac

# Don't include s390x until it is explicitly requested, as it is unlikely to
# work by default.
# Don't attempt ppc64le until there's a package for recent LTS versions.
# See https://github.com/openzipkin/zipkin/issues/3443
export DOCKER_ARCHS="amd64 arm64"

build-bin/docker/docker_push openzipkin/zipkin-dependencies ${version}
