#!/bin/sh
#
# Copyright 2015-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

# This script is only a convenience as the build environment is controlled in
# the Dockerfile. That said, it uses only basic shell commands to help it work
# on developer laptops as well as CI nodes. Mainly, this centralizes the base
# Java image mappings and ensures all metadata needed is taken from pom.xml.
set -ue

if ! test -f docker/Dockerfile; then
  echo Please execute this script from the repository root
  exit 1
fi

PROJECT="Zipkin Dependencies"
TAG=${1:-openzipkin/zipkin-dependencies:test}
# Default the version to the pom when unset
POM_VERSION=${POM_VERSION:-$(mvn help:evaluate -N -Dexpression=project.version -q -DforceStdout)}
RELEASE_VERSION=${2:-${POM_VERSION}}
OP=${3:-load}

TARGET=$(echo $TAG|sed -e 's~.*/\(.*\):.*~\1~g')
# When true use zipkin-dependencies.jar produced by a Maven build.
# This is implicitly true when a SNAPSHOT version.
RELEASE_FROM_MAVEN_BUILD=${RELEASE_FROM_MAVEN_BUILD:-false}

# Until we can upgrade to Spark 3, we are pinned to JRE 1.8
JAVA_VERSION=${JAVA_VERSION:-8.252.09}

# Platforms to eventually push to the registry
PLATFORMS="linux/amd64,linux/arm64"
DOCKERFILE_PATH=docker/Dockerfile

# We don't currently release from a remote snapshot repository. When the version is snapshot, this
# is a local build or a pull request. Look to see if the files the build would produce are present.
# This allows skipping the build when an upstream step or stage has already produced them.
case "${RELEASE_VERSION}" in
  *-SNAPSHOT )
    if [ -f "main/target/zipkin-dependencies-${RELEASE_VERSION}.jar" ]; then
      echo Re-using ${PROJECT} ${RELEASE_VERSION} binaries from a previous build...
    elif [ ${RELEASE_FROM_MAVEN_BUILD} = true ]; then
      echo "RELEASE_FROM_MAVEN_BUILD=true, but required binaries are not present"
      exit 1
    else
      if [ ${RELEASE_VERSION} != ${POM_VERSION} ]; then
        echo "To build ${PROJECT} implicitly, run: docker/build_image ${TAG} ${POM_VERSION}"
        exit 1
      fi

      echo Building ${PROJECT} ${RELEASE_VERSION}...
      ./mvnw -T1C -q --batch-mode -DskipTests -Dlicense.skip=true -Denforcer.fail=false --also-make -pl main package
    fi
    RELEASE_FROM_MAVEN_BUILD=true
    ;;
esac

DOCKER_ARGS="-f ${DOCKERFILE_PATH} --target ${TARGET} --tag ${TAG} \
--build-arg release_version=${RELEASE_VERSION} --label zipkin-dependencies-version=${RELEASE_VERSION} \
--build-arg release_from_maven_build=${RELEASE_FROM_MAVEN_BUILD} \
--build-arg java_version=${JAVA_VERSION} \
--label org.opencontainers.image.source=https://github.com/openzipkin/zipkin-dependencies \
--label org.opencontainers.image.version=${RELEASE_VERSION} ."

# Avoid buildx for two reasons:
#  * It only supports one platform/arch on load https://github.com/docker/buildx/issues/59
#  * It would pull Docker Hub for moby/buildkit or multiarch/qemu-user-static images, using up quota
if [ "${OP}" = "load" ]; then
  echo "Building image ${TAG} with java_version ${JAVA_VERSION}"
  docker build ${DOCKER_ARGS}
  exit $?
fi

if [ "${OP}" != "push" ]; then
  echo "Invalid OP: ${OP}, Ex. load or push"
  exit 1
fi

# This can be less manual in the future, for example checking buildx to see what it can do.
ARCH=${ARCH:-$(uname -m)}
case ${ARCH} in
  x86_64* )
    ;;
  amd64* )
    ;;
  * )
    echo Pushing platforms ${PLATFORMS} with arch ${ARCH} is not yet supported.
    exit 1
esac

echo "Pushing image ${TAG} with platforms ${PLATFORMS} and Java version ${JAVA_VERSION}"
docker buildx build --progress plain --platform=${PLATFORMS} ${DOCKER_ARGS} --push
